dist: trusty
#sudo: required

language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11
  # - openjdk8

before_install: true

install: true

script: 
  - mvn clean package -Dmaven.test.skip=true
  - mvn clean test -pl jdbc -am -Dtsfile.test.skip=true

after_success:

