dist: trusty
#sudo: required

language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11
  # - openjdk8

before_install: true

install: true

script: 
  - mvn clean package -Dmaven.test.skip=true
  - mvn clean test -pl iotdb -am -Dtsfile.test.skip=true -Djdbc.test.skip=true -Dit.test.excludes="**/IoTDB*Test.java"

after_success:

